// Package sweexplore implements the repository-owned orchestration boundary for
// the warm-index SWE-Explore benchmark defined by ADR-0030.
package sweexplore

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// SchemaVersion is the only configuration and artifact schema understood by
// this build. Refusing unknown versions prevents a campaign from silently
// changing meaning after a harness update.
const SchemaVersion = 1

// maxFreshnessTimeout bounds only unmeasured checkout/index preparation. Large
// repositories on local hardware can legitimately exceed the paid arm limit;
// twelve hours still prevents an abandoned campaign from waiting forever.
const maxFreshnessTimeout = 12 * time.Hour

// Mode identifies whether an arm is the native control or the LCTK treatment.
type Mode string

const (
	// ModeNative is a client run with no LCTK MCP server available.
	ModeNative Mode = "native"
	// ModeLCTK is a client run with the approved project-bound LCTK MCP server.
	ModeLCTK Mode = "lctk"
)

// Provider selects the trace adapter and the exact isolation flags generated by
// the harness. Supporting named providers instead of arbitrary shell strings is
// what makes arm isolation auditable.
type Provider string

const (
	// ProviderCodex selects Codex CLI non-interactive JSONL mode.
	ProviderCodex Provider = "codex"
	// ProviderClaude selects Claude Code non-interactive stream-JSON mode.
	ProviderClaude Provider = "claude"
	// ProviderFixture selects the deterministic test helper used only by tests.
	ProviderFixture Provider = "fixture"
)

// Config is the complete immutable input to one benchmark campaign.
type Config struct {
	SchemaVersion int             `json:"schema_version"`
	Benchmark     BenchmarkConfig `json:"benchmark"`
	Workspace     WorkspaceConfig `json:"workspace"`
	Run           RunConfig       `json:"run"`
	Arms          []ArmConfig     `json:"arms"`
}

// BenchmarkConfig pins the two joined datasets and the official evaluator.
type BenchmarkConfig struct {
	ExploreDatasetPath   string `json:"explore_dataset_path"`
	ExploreDatasetSHA256 string `json:"explore_dataset_sha256"`
	IssueDatasetPath     string `json:"issue_dataset_path"`
	IssueDatasetSHA256   string `json:"issue_dataset_sha256"`
	OfficialRoot         string `json:"official_root"`
	OfficialCommit       string `json:"official_commit"`
}

// WorkspaceConfig identifies the one stable registered project whose checkout
// is changed sequentially between benchmark instances.
type WorkspaceConfig struct {
	Root                    string `json:"root"`
	ProjectID               string `json:"project_id"`
	LCTKExecutable          string `json:"lctk_executable"`
	ExpectedLCTKVersion     string `json:"expected_lctk_version"`
	FreshnessTimeoutSeconds int    `json:"freshness_timeout_seconds"`
}

// RunConfig fixes the limits that must be identical across paired arms.
type RunConfig struct {
	TopK           int `json:"top_k"`
	TimeoutSeconds int `json:"timeout_seconds"`
}

// ArmConfig describes one provider-specific control or treatment arm. The MCP
// file contains only a public endpoint; OAuth credentials remain client-owned.
type ArmConfig struct {
	ID            string   `json:"id"`
	Provider      Provider `json:"provider"`
	Mode          Mode     `json:"mode"`
	Executable    string   `json:"executable"`
	Model         string   `json:"model"`
	Effort        string   `json:"effort,omitempty"`
	MCPConfigPath string   `json:"mcp_config_path,omitempty"`
	MCPServerName string   `json:"mcp_server_name,omitempty"`
}

// Region is one ordered, one-based, inclusive prediction interval.
type Region struct {
	Path  string `json:"path"`
	Start int    `json:"start"`
	End   int    `json:"end"`
}

// GroundTruth is the subset of the public SWE-Explore schema used for local
// validation and parity tests. Unknown upstream fields remain untouched.
type GroundTruth struct {
	ReadCoreFiles          []string            `json:"read_core_files"`
	ReadCoreRegions        []Region            `json:"read_core_regions"`
	ReadOptionalFilesMap   map[string][]string `json:"read_optional_files_map"`
	ReadOptionalRegionsMap map[string][]Region `json:"read_optional_regions_map"`
	MainFiles              []string            `json:"main_files"`
}

// ExploreRecord is one unchanged public benchmark row.
type ExploreRecord struct {
	InstanceID  string      `json:"instance_id"`
	GroundTruth GroundTruth `json:"ground_truth"`
}

// IssueRecord supplies the fields intentionally absent from the public
// SWE-Explore data.
type IssueRecord struct {
	InstanceID       string `json:"instance_id"`
	Repository       string `json:"repo"`
	BaseCommit       string `json:"base_commit"`
	ProblemStatement string `json:"problem_statement"`
}

// Instance is the exact joined task given to an agent.
type Instance struct {
	InstanceID       string
	Repository       string
	BaseCommit       string
	ProblemStatement string
	GroundTruth      GroundTruth
}

// Usage preserves provider-reported token accounting without inventing missing
// fields. Zero means the client did not report that category.
type Usage struct {
	InputTokens              int64 `json:"input_tokens,omitempty"`
	CachedInputTokens        int64 `json:"cached_input_tokens,omitempty"`
	CacheCreationInputTokens int64 `json:"cache_creation_input_tokens,omitempty"`
	OutputTokens             int64 `json:"output_tokens,omitempty"`
	ReasoningOutputTokens    int64 `json:"reasoning_output_tokens,omitempty"`
}

// ProviderMetrics retains client-reported measurements whose meaning is not
// identical across providers. Keeping them separate from wall-clock time and
// normalized token usage prevents the aggregate report from inventing parity.
type ProviderMetrics struct {
	ReportedCostUSD float64 `json:"reported_cost_usd,omitempty"`
	DurationMS      int64   `json:"duration_ms,omitempty"`
	APIDurationMS   int64   `json:"api_duration_ms,omitempty"`
	Turns           int64   `json:"turns,omitempty"`
}

// FreshnessProof records the exact pre-measurement state required by ADR-0030.
type FreshnessProof struct {
	ProjectID          string `json:"project_id"`
	Version            string `json:"version"`
	ExactGeneration    uint64 `json:"exact_generation"`
	SemanticGeneration uint64 `json:"semantic_generation"`
	GraphGeneration    uint64 `json:"graph_generation"`
	WatcherGeneration  uint64 `json:"watcher_generation"`
	WatcherSequence    uint64 `json:"watcher_sequence"`
	WatcherCheckpoint  uint64 `json:"watcher_checkpoint"`
	WatcherPending     int    `json:"watcher_pending"`
	ObservedAt         string `json:"observed_at"`
}

// Result is the durable record for one paid or synthetic agent turn.
type Result struct {
	SchemaVersion int             `json:"schema_version"`
	InstanceID    string          `json:"instance_id"`
	ArmID         string          `json:"arm_id"`
	Provider      Provider        `json:"provider"`
	Mode          Mode            `json:"mode"`
	Model         string          `json:"model"`
	ClientVersion string          `json:"client_version"`
	BaseCommit    string          `json:"base_commit"`
	StartedAt     string          `json:"started_at"`
	ElapsedMS     int64           `json:"elapsed_ms"`
	ExitCode      int             `json:"exit_code"`
	Regions       []Region        `json:"regions"`
	LCTKToolCalls []string        `json:"lctk_tool_calls"`
	ActualModels  []string        `json:"actual_models,omitempty"`
	Usage         Usage           `json:"usage"`
	ProviderStats ProviderMetrics `json:"provider_metrics,omitempty"`
	Freshness     *FreshnessProof `json:"freshness,omitempty"`
	RawTracePath  string          `json:"raw_trace_path"`
}

// LoadConfig reads and validates a configuration without changing any external
// state, which is the first stage of every dry run and execution.
func LoadConfig(path string) (Config, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		return Config{}, fmt.Errorf("read benchmark config: %w", err)
	}
	var config Config
	decoder := json.NewDecoder(strings.NewReader(string(body)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&config); err != nil {
		return Config{}, fmt.Errorf("decode benchmark config: %w", err)
	}
	if err := config.Validate(filepath.Dir(path)); err != nil {
		return Config{}, err
	}
	return config, nil
}

// Validate rejects incomplete or ambiguous campaign inputs before an agent can
// consume budget.
func (config *Config) Validate(configDir string) error {
	if config.SchemaVersion != SchemaVersion {
		return fmt.Errorf("unsupported benchmark schema %d", config.SchemaVersion)
	}
	if config.Run.TopK <= 0 || config.Run.TopK > 100 {
		return errors.New("run.top_k must be between 1 and 100")
	}
	if config.Run.TimeoutSeconds <= 0 || time.Duration(config.Run.TimeoutSeconds)*time.Second > 2*time.Hour {
		return errors.New("run.timeout_seconds must be between 1 and 7200")
	}
	for name, value := range map[string]string{
		"benchmark.explore_dataset_path":  config.Benchmark.ExploreDatasetPath,
		"benchmark.issue_dataset_path":    config.Benchmark.IssueDatasetPath,
		"benchmark.official_root":         config.Benchmark.OfficialRoot,
		"workspace.root":                  config.Workspace.Root,
		"workspace.project_id":            config.Workspace.ProjectID,
		"workspace.lctk_executable":       config.Workspace.LCTKExecutable,
		"workspace.expected_lctk_version": config.Workspace.ExpectedLCTKVersion,
	} {
		if strings.TrimSpace(value) == "" {
			return fmt.Errorf("%s is required", name)
		}
	}
	config.Benchmark.ExploreDatasetPath = resolveConfigPath(configDir, config.Benchmark.ExploreDatasetPath)
	config.Benchmark.IssueDatasetPath = resolveConfigPath(configDir, config.Benchmark.IssueDatasetPath)
	config.Benchmark.OfficialRoot = resolveConfigPath(configDir, config.Benchmark.OfficialRoot)
	config.Workspace.Root = resolveConfigPath(configDir, config.Workspace.Root)
	config.Workspace.LCTKExecutable = resolveConfigPath(configDir, config.Workspace.LCTKExecutable)
	if config.Workspace.FreshnessTimeoutSeconds <= 0 || time.Duration(config.Workspace.FreshnessTimeoutSeconds)*time.Second > maxFreshnessTimeout {
		return errors.New("workspace.freshness_timeout_seconds must be between 1 and 43200")
	}
	seen := map[string]struct{}{}
	for index := range config.Arms {
		arm := &config.Arms[index]
		if arm.ID == "" || arm.Executable == "" || arm.Model == "" {
			return fmt.Errorf("arm %d requires id, executable, and model", index)
		}
		if _, duplicate := seen[arm.ID]; duplicate {
			return fmt.Errorf("duplicate arm id %q", arm.ID)
		}
		seen[arm.ID] = struct{}{}
		if arm.Mode != ModeNative && arm.Mode != ModeLCTK {
			return fmt.Errorf("arm %q has unsupported mode %q", arm.ID, arm.Mode)
		}
		if arm.Provider != ProviderCodex && arm.Provider != ProviderClaude {
			return fmt.Errorf("arm %q has unsupported provider %q", arm.ID, arm.Provider)
		}
		if arm.Mode == ModeLCTK {
			if arm.MCPConfigPath == "" || arm.MCPServerName == "" {
				return fmt.Errorf("LCTK arm %q requires mcp_config_path and mcp_server_name", arm.ID)
			}
			arm.MCPConfigPath = resolveConfigPath(configDir, arm.MCPConfigPath)
		} else if arm.MCPConfigPath != "" || arm.MCPServerName != "" {
			return fmt.Errorf("native arm %q must not name an MCP configuration", arm.ID)
		}
	}
	if len(config.Arms) == 0 {
		return errors.New("at least one arm is required")
	}
	for _, provider := range []Provider{ProviderCodex, ProviderClaude} {
		var native, treatment *ArmConfig
		for index := range config.Arms {
			arm := &config.Arms[index]
			if arm.Provider != provider {
				continue
			}
			if arm.Mode == ModeNative {
				if native != nil {
					return fmt.Errorf("provider %q has more than one native arm", provider)
				}
				native = arm
			} else {
				if treatment != nil {
					return fmt.Errorf("provider %q has more than one LCTK arm", provider)
				}
				treatment = arm
			}
		}
		if native == nil || treatment == nil {
			return fmt.Errorf("provider %q requires exactly one native and one LCTK arm", provider)
		}
		if native.Executable != treatment.Executable || native.Model != treatment.Model || native.Effort != treatment.Effort {
			return fmt.Errorf("provider %q paired arms must use the same executable, model, and effort", provider)
		}
	}
	if len(config.Arms) != 4 {
		return fmt.Errorf("campaign requires exactly four paired arms, got %d", len(config.Arms))
	}
	return nil
}

// Arm returns one exact configured arm instead of accepting ambiguous prefixes.
func (config Config) Arm(id string) (ArmConfig, error) {
	for _, arm := range config.Arms {
		if arm.ID == id {
			return arm, nil
		}
	}
	return ArmConfig{}, fmt.Errorf("benchmark arm %q is not configured", id)
}

func resolveConfigPath(base, value string) string {
	if filepath.IsAbs(value) {
		return filepath.Clean(value)
	}
	return filepath.Clean(filepath.Join(base, value))
}
