package projectstack

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/lev-goryachev/lctk/internal/buildinfo"
	"github.com/lev-goryachev/lctk/internal/projectregistry"
)

// ErrInvalidProject reports a project that cannot be turned into a stack.
var ErrInvalidProject = errors.New("project cannot be used as a container stack")

// The Compose document is modelled with structs rather than maps so that the
// rendered bytes are deterministic. Go marshals struct fields in declaration
// order, whereas map iteration order is unspecified, and Slice 1.2 requires that
// generated configuration be reproducible.

type composeFile struct {
	Name     string          `yaml:"name"`
	Services composeServices `yaml:"services"`
	Networks composeNetworks `yaml:"networks"`
	Volumes  composeVolumes  `yaml:"volumes"`
}

type composeServices struct {
	CodeIntel composeService `yaml:"code-intel"`
}

type composeService struct {
	Image         string             `yaml:"image"`
	ContainerName string             `yaml:"container_name"`
	Init          bool               `yaml:"init"`
	Restart       string             `yaml:"restart"`
	Environment   []string           `yaml:"environment"`
	Volumes       []composeMount     `yaml:"volumes"`
	Networks      []string           `yaml:"networks"`
	Healthcheck   composeHealthcheck `yaml:"healthcheck"`
	Labels        []string           `yaml:"labels"`
}

// composeMount uses Compose long syntax deliberately. Short syntax separates
// fields with colons, which is ambiguous for a Windows path such as C:\work, so
// long syntax is a correctness requirement on the primary host platform rather
// than a style preference.
type composeMount struct {
	Type     string `yaml:"type"`
	Source   string `yaml:"source"`
	Target   string `yaml:"target"`
	ReadOnly bool   `yaml:"read_only,omitempty"`
}

type composeHealthcheck struct {
	Test        []string `yaml:"test"`
	Interval    string   `yaml:"interval"`
	Timeout     string   `yaml:"timeout"`
	Retries     int      `yaml:"retries"`
	StartPeriod string   `yaml:"start_period"`
}

type composeNetworks struct {
	Project composeNetwork `yaml:"project"`
}

type composeNetwork struct {
	Name   string `yaml:"name"`
	Driver string `yaml:"driver"`
}

type composeVolumes struct {
	State composeVolume `yaml:"state"`
}

type composeVolume struct {
	Name string `yaml:"name"`
}

// Render produces the Compose document for one project.
//
// The output is a pure function of the project record and the product version, so
// rendering the same project twice yields identical bytes. Nothing time-based,
// random, or environment-dependent may enter this function.
func Render(project projectregistry.Project) ([]byte, error) {
	names, err := DeriveNames(project.ID)
	if err != nil {
		return nil, err
	}
	if project.Path == "" {
		return nil, fmt.Errorf("%w: project %s has no host path", ErrInvalidProject, project.ID)
	}
	if !filepath.IsAbs(project.Path) {
		return nil, fmt.Errorf("%w: host path %q is not absolute", ErrInvalidProject, project.Path)
	}

	document := composeFile{
		Name: names.ComposeName,
		Services: composeServices{
			CodeIntel: composeService{
				Image:         names.Image,
				ContainerName: names.ContainerName,
				Init:          true,
				// The stack is started and stopped explicitly by LCTK, so a
				// container must not come back on its own after a stop.
				Restart: "no",
				Environment: []string{
					"LCTK_PROJECT_ID=" + project.ID,
					"LCTK_PROJECT_PROFILE=" + string(project.Profile),
					"LCTK_WORKSPACE=" + WorkspaceMount,
					"LCTK_STATE_DIR=" + StateMount,
				},
				Volumes: []composeMount{
					{
						Type:   "bind",
						Source: project.Path,
						Target: WorkspaceMount,
						// The code-intel boundary never writes to the working
						// tree. A writable mount belongs to the future runner.
						ReadOnly: true,
					},
					{
						Type:   "volume",
						Source: "state",
						Target: StateMount,
					},
				},
				Networks: []string{"project"},
				Healthcheck: composeHealthcheck{
					Test:        []string{"CMD", "test", "-f", StateMount + "/ready"},
					Interval:    "5s",
					Timeout:     "3s",
					Retries:     6,
					StartPeriod: "2s",
				},
				Labels: []string{
					"tech.lctk.project-id=" + project.ID,
					"tech.lctk.managed=true",
					"tech.lctk.version=" + buildinfo.Version,
				},
			},
		},
		Networks: composeNetworks{
			Project: composeNetwork{Name: names.Network, Driver: "bridge"},
		},
		Volumes: composeVolumes{
			State: composeVolume{Name: names.Volume},
		},
	}

	body, err := yaml.Marshal(document)
	if err != nil {
		return nil, fmt.Errorf("render compose for %s: %w", project.ID, err)
	}

	header := "# Generated by LCTK. Do not edit: this file is rewritten from the\n" +
		"# registry whenever the project starts, and the registry is authoritative.\n"
	return append([]byte(header), body...), nil
}

// Write renders the Compose document and stores it under the LCTK home.
//
// The write is atomic so an interrupted start cannot leave a half-written file
// that Compose would later refuse or, worse, misread.
func Write(project projectregistry.Project) (string, error) {
	body, err := Render(project)
	if err != nil {
		return "", err
	}

	dir, err := StackDir(project.ID)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("create stack directory %q: %w", dir, err)
	}

	path := filepath.Join(dir, "compose.yaml")
	temp, err := os.CreateTemp(dir, "compose.*.tmp")
	if err != nil {
		return "", fmt.Errorf("create temporary compose file in %q: %w", dir, err)
	}
	tempName := temp.Name()
	defer os.Remove(tempName)

	if _, err := temp.Write(body); err != nil {
		temp.Close()
		return "", fmt.Errorf("write temporary compose file: %w", err)
	}
	if err := temp.Sync(); err != nil {
		temp.Close()
		return "", fmt.Errorf("flush temporary compose file: %w", err)
	}
	if err := temp.Close(); err != nil {
		return "", fmt.Errorf("close temporary compose file: %w", err)
	}
	if err := os.Chmod(tempName, 0o600); err != nil {
		return "", fmt.Errorf("restrict temporary compose file permissions: %w", err)
	}
	if err := os.Rename(tempName, path); err != nil {
		return "", fmt.Errorf("replace compose file %q: %w", path, err)
	}
	return path, nil
}
