package main

import (
	"fmt"
	"sort"
	"strings"
)

// codexServerEntry is the LCTK-relevant subset of a Codex `mcp_servers` entry
// for a Streamable HTTP server, as verified against codex-cli 0.146.0-alpha.9.2.
//
// Secrets are intentionally not representable here. Codex rejects an inline
// `bearer_token` for a streamable_http server, so the token is always referenced
// by environment-variable name.
type codexServerEntry struct {
	Name              string
	URL               string
	BearerTokenEnvVar string
	StartupTimeoutSec float64
	ToolTimeoutSec    float64
	Enabled           bool
	HTTPHeaders       map[string]string
	EnvHTTPHeaders    map[string]string
}

// tomlEscape quotes a TOML basic string. Codex parses config.toml strictly, so
// generated values must be escaped rather than interpolated.
func tomlEscape(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// tomlKey renders a table key, quoting it when it is not a bare key.
func tomlKey(s string) string {
	if s == "" {
		return `""`
	}
	for _, r := range s {
		isBare := r == '_' || r == '-' ||
			(r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')
		if !isBare {
			return tomlEscape(s)
		}
	}
	return s
}

// render writes the entry as TOML. Key order is deterministic so generated
// configuration is reproducible.
func (e codexServerEntry) render() string {
	var b strings.Builder
	table := "mcp_servers." + tomlKey(e.Name)
	fmt.Fprintf(&b, "[%s]\n", table)
	fmt.Fprintf(&b, "url = %s\n", tomlEscape(e.URL))
	if e.BearerTokenEnvVar != "" {
		fmt.Fprintf(&b, "bearer_token_env_var = %s\n", tomlEscape(e.BearerTokenEnvVar))
	}
	if e.StartupTimeoutSec > 0 {
		fmt.Fprintf(&b, "startup_timeout_sec = %s\n", trimFloat(e.StartupTimeoutSec))
	}
	if e.ToolTimeoutSec > 0 {
		fmt.Fprintf(&b, "tool_timeout_sec = %s\n", trimFloat(e.ToolTimeoutSec))
	}
	fmt.Fprintf(&b, "enabled = %t\n", e.Enabled)

	if len(e.HTTPHeaders) > 0 {
		fmt.Fprintf(&b, "\n[%s.http_headers]\n", table)
		writeStringTable(&b, e.HTTPHeaders)
	}
	if len(e.EnvHTTPHeaders) > 0 {
		fmt.Fprintf(&b, "\n[%s.env_http_headers]\n", table)
		writeStringTable(&b, e.EnvHTTPHeaders)
	}
	return b.String()
}

func writeStringTable(b *strings.Builder, m map[string]string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(b, "%s = %s\n", tomlKey(k), tomlEscape(m[k]))
	}
}

func trimFloat(f float64) string {
	s := fmt.Sprintf("%.3f", f)
	s = strings.TrimRight(s, "0")
	return strings.TrimSuffix(s, ".")
}

// renderCodexHomeConfig renders a complete isolated CODEX_HOME config.toml.
//
// This models what LCTK would have to generate. Codex discovers MCP servers only
// through CODEX_HOME/config.toml, so there is no project-local file to emit.
func renderCodexHomeConfig(entries []codexServerEntry) string {
	var b strings.Builder
	b.WriteString("# Generated by the LCTK Slice 0.4 Codex compatibility harness.\n")
	b.WriteString("# Codex discovers MCP servers only through CODEX_HOME/config.toml.\n")
	b.WriteString("# Secrets are referenced by environment-variable name, never inlined.\n")
	sorted := make([]codexServerEntry, len(entries))
	copy(sorted, entries)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	for _, e := range sorted {
		b.WriteString("\n")
		b.WriteString(e.render())
	}
	return b.String()
}
